In [1]:
import pandas as pd

In [2]:
import os 
cwd = os.getcwd() 
print("Current working directory:", cwd)

Current working directory: e:\code\python\deployAI\ModelAI\notebook

In [3]:
os.chdir('../')
cwd = os.getcwd() 
print("Current working directory:", cwd)

Current working directory: e:\code\python\deployAI\ModelAI

In [11]:
file_path = 'E:\code\python\deployAI\ModelAI\data/book_rating_with_langcode_eng_only.csv'
columns_to_read = ['User-ID','Book-Rating','isbn','Location','Age']
ratings = pd.read_csv(file_path, usecols=columns_to_read)
print(ratings)

        User-ID  Book-Rating        isbn                          Location  \
0        276727            0  0446520802     h, new south wales, australia
1        278418            0  0446520802              omaha, nebraska, usa
2        278418            0  055356451X              omaha, nebraska, usa
3        278418            0  0446364193              omaha, nebraska, usa
4        278418            0  0449217264              omaha, nebraska, usa
...         ...          ...         ...                               ...
386280   274446            4  0451526023              cleveland, ohio, usa
386281   274839            0  3442133173     zÃ¼rich, zÃ¼rich, switzerland
386282   275163            7  1569313725       gaithersburg, maryland, usa
386283   275531            0  1880238136        little rock, arkansas, usa
386284   276647            0  0553571001  arlington heights, illinois, usa

         Age
0       16.0
1        NaN
2        NaN
3        NaN
4        NaN
...      ...
386280  22.0
386281  50.0
386282   NaN
386283   NaN
386284  13.0

[386285 rows x 5 columns]

In [12]:
file_path_book = 'E:\code\python\deployAI\ModelAI\data/book-average-rating-with-langcode-eng-only.csv'
# columns_to_read = ['User-ID','Book-Rating','isbn','Location','Age']
books = pd.read_csv(file_path_book)
print(books)

               id                                 title  \
0      0001053744                   Pearl and Sir Orfeo
1      0001821504          The Adventures of Paddington
2      0001837397                          Autumn Story
3      000184251X  February's Road (Callendars, Book 2)
4      0001981625                The Sea Of Tranquility
...           ...                                   ...
50917  9997410440                    Nine Hours to Rama
50918  9997412958                       The White Witch
50919  9997531590                           World's End
50920  9997555627                  My Sweet Orange Tree
50921  9999669972                         Being Bullied

                         authors  \
0               J. R. R. Tolkien
1                   Michael Bond
2                   Jill Barklem
3                    John Verney
4                    Mark Haddon
...                          ...
50917            Stanley Wolpert
50918           Elizabeth Goudge
50919             Upton Sinclair
50920  Jose Mauro De Vasconcelos
50921                  Joy Berry

                                             description book_cover  \
0      This 14th-century poem, translated into modern...  Audiobook
1      The Adventures of Paddingtonis a special editi...  Hardcover
2      Step into the exquisite miniature world of the...  Hardcover
3      Augustus Callendar, a newspaper correspondent,...        NaN
4      Leading up to the 40th anniversary of the firs...  Hardcover
...                                                  ...        ...
50917  "This is a terrifying, yet inspiring novel. As...  Hardcover
50918  Romantic tale set in 17th-century England, whe...        NaN
50919  World's End is the first novel in Upton Sincla...        NaN
50920  Five-year-old Zeze lives in Rio de Janeiro, in...  Hardcover
50921  Help Me Be Good About Being Bullied explains w...  Hardcover

                                               image_url release_date  \
0      https://s.gr-assets.com/assets/nophoto/book/11...          NaN
1      https://s.gr-assets.com/assets/nophoto/book/11...   1970-01-01
2      https://images.gr-assets.com/books/1356441145m...          NaN
3      https://s.gr-assets.com/assets/nophoto/book/11...   1987-01-01
4      https://images.gr-assets.com/books/1333629650m...          NaN
...                                                  ...          ...
50917  https://images.gr-assets.com/books/1339793012m...   1962-01-01
50918  https://images.gr-assets.com/books/1259357850m...   1958-01-01
50919  https://images.gr-assets.com/books/1347542920m...          NaN
50920  https://images.gr-assets.com/books/1319973122m...          NaN
50921  https://images.gr-assets.com/books/1494546931m...   1989-01-01

                         publisher  number_of_pages  average_rating  \
0      Trafalgar Square Publishing              2.0            3.90
1         HarperCollins Publishers              NaN            4.13
2      William Collins Sons Co Ltd              NaN            4.43
3         HarperCollins Publishers              NaN            4.50
4         HarperCollins Publishers             32.0            3.57
...                            ...              ...             ...
50917             Random House (T)            376.0            3.75
50918         Putnam Pub Group (T)              NaN            3.99
50919              Penguin USA (T)              NaN            4.02
50920             Random House (T)            208.0            4.37
50921                Smithmark Pub              NaN            3.78

       number_of_ratings            categories        isbn  \
0                     30            ['Poetry']  0001053744
1                    203          ['Children']  0001821504
2                     34          ['Children']  0001837397
3                     20          ['Children']  000184251X
4                     83          ['Children']  0001981625
...                  ...                   ...         ...
50917                 51  ['History, Biology']  9997410440
50918                 10  ['History, Biology']  9997412958
50919                298  ['History, Biology']  9997531590
50920                685          ['Children']  9997555627
50921                 12          ['Children']  9999669972

       new_average_rating  new_number_of_ratings
0                     5.0                      1
1                     0.0                      1
2                     3.0                      3
3                     0.0                      2
4                     4.0                      2
...                   ...                    ...
50917                10.0                      1
50918                10.0                      1
50919                 0.0                      1
50920                 0.0                      1
50921                 0.0                      1

[50922 rows x 15 columns]

In [13]:
books.dtypes

id                        object
title                     object
authors                   object
description               object
book_cover                object
image_url                 object
release_date              object
publisher                 object
number_of_pages          float64
average_rating           float64
number_of_ratings          int64
categories                object
isbn                      object
new_average_rating       float64
new_number_of_ratings      int64
dtype: object

In [14]:
books.isna().sum()

id                           0
title                        0
authors                      0
description                  0
book_cover                5909
image_url                    0
release_date             45896
publisher                    0
number_of_pages           7850
average_rating               0
number_of_ratings            0
categories                   0
isbn                         0
new_average_rating           0
new_number_of_ratings        0
dtype: int64

In [15]:
books.drop(columns=['average_rating', 'number_of_ratings'])

,id,title,authors,description,book_cover,image_url,release_date,publisher,number_of_pages,categories,isbn,new_average_rating,new_number_of_ratings
0,0001053744,Pearl and Sir Orfeo,J. R. R. Tolkien,"This 14th-century poem, translated into modern...",Audiobook,https://s.gr-assets.com/assets/nophoto/book/11...,NaN,Trafalgar Square Publishing,2.0,['Poetry'],0001053744,5.0,1
1,0001821504,The Adventures of Paddington,Michael Bond,The Adventures of Paddingtonis a special editi...,Hardcover,https://s.gr-assets.com/assets/nophoto/book/11...,1970-01-01,HarperCollins Publishers,NaN,['Children'],0001821504,0.0,1
2,0001837397,Autumn Story,Jill Barklem,Step into the exquisite miniature world of the...,Hardcover,https://images.gr-assets.com/books/1356441145m...,NaN,William Collins Sons Co Ltd,NaN,['Children'],0001837397,3.0,3
3,000184251X,"February's Road (Callendars, Book 2)",John Verney,"Augustus Callendar, a newspaper correspondent,...",NaN,https://s.gr-assets.com/assets/nophoto/book/11...,1987-01-01,HarperCollins Publishers,NaN,['Children'],000184251X,0.0,2
4,0001981625,The Sea Of Tranquility,Mark Haddon,Leading up to the 40th anniversary of the firs...,Hardcover,https://images.gr-assets.com/books/1333629650m...,NaN,HarperCollins Publishers,32.0,['Children'],0001981625,4.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50917,9997410440,Nine Hours to Rama,Stanley Wolpert,"""This is a terrifying, yet inspiring novel. As...",Hardcover,https://images.gr-assets.com/books/1339793012m...,1962-01-01,Random House (T),376.0,"['History, Biology']",9997410440,10.0,1
50918,9997412958,The White Witch,Elizabeth Goudge,"Romantic tale set in 17th-century England, whe...",NaN,https://images.gr-assets.com/books/1259357850m...,1958-01-01,Putnam Pub Group (T),NaN,"['History, Biology']",9997412958,10.0,1
50919,9997531590,World's End,Upton Sinclair,World's End is the first novel in Upton Sincla...,NaN,https://images.gr-assets.com/books/1347542920m...,NaN,Penguin USA (T),NaN,"['History, Biology']",9997531590,0.0,1
50920,9997555627,My Sweet Orange Tree,Jose Mauro De Vasconcelos,"Five-year-old Zeze lives in Rio de Janeiro, in...",Hardcover,https://images.gr-assets.com/books/1319973122m...,NaN,Random House (T),208.0,['Children'],9997555627,0.0,1
50921,9999669972,Being Bullied,Joy Berry,Help Me Be Good About Being Bullied explains w...,Hardcover,https://images.gr-assets.com/books/1494546931m...,1989-01-01,Smithmark Pub,NaN,['Children'],9999669972,0.0,1

In [16]:
books.drop(columns=['id'])

,title,authors,description,book_cover,image_url,release_date,publisher,number_of_pages,average_rating,number_of_ratings,categories,isbn,new_average_rating,new_number_of_ratings
0,Pearl and Sir Orfeo,J. R. R. Tolkien,"This 14th-century poem, translated into modern...",Audiobook,https://s.gr-assets.com/assets/nophoto/book/11...,NaN,Trafalgar Square Publishing,2.0,3.90,30,['Poetry'],0001053744,5.0,1
1,The Adventures of Paddington,Michael Bond,The Adventures of Paddingtonis a special editi...,Hardcover,https://s.gr-assets.com/assets/nophoto/book/11...,1970-01-01,HarperCollins Publishers,NaN,4.13,203,['Children'],0001821504,0.0,1
2,Autumn Story,Jill Barklem,Step into the exquisite miniature world of the...,Hardcover,https://images.gr-assets.com/books/1356441145m...,NaN,William Collins Sons Co Ltd,NaN,4.43,34,['Children'],0001837397,3.0,3
3,"February's Road (Callendars, Book 2)",John Verney,"Augustus Callendar, a newspaper correspondent,...",NaN,https://s.gr-assets.com/assets/nophoto/book/11...,1987-01-01,HarperCollins Publishers,NaN,4.50,20,['Children'],000184251X,0.0,2
4,The Sea Of Tranquility,Mark Haddon,Leading up to the 40th anniversary of the firs...,Hardcover,https://images.gr-assets.com/books/1333629650m...,NaN,HarperCollins Publishers,32.0,3.57,83,['Children'],0001981625,4.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50917,Nine Hours to Rama,Stanley Wolpert,"""This is a terrifying, yet inspiring novel. As...",Hardcover,https://images.gr-assets.com/books/1339793012m...,1962-01-01,Random House (T),376.0,3.75,51,"['History, Biology']",9997410440,10.0,1
50918,The White Witch,Elizabeth Goudge,"Romantic tale set in 17th-century England, whe...",NaN,https://images.gr-assets.com/books/1259357850m...,1958-01-01,Putnam Pub Group (T),NaN,3.99,10,"['History, Biology']",9997412958,10.0,1
50919,World's End,Upton Sinclair,World's End is the first novel in Upton Sincla...,NaN,https://images.gr-assets.com/books/1347542920m...,NaN,Penguin USA (T),NaN,4.02,298,"['History, Biology']",9997531590,0.0,1
50920,My Sweet Orange Tree,Jose Mauro De Vasconcelos,"Five-year-old Zeze lives in Rio de Janeiro, in...",Hardcover,https://images.gr-assets.com/books/1319973122m...,NaN,Random House (T),208.0,4.37,685,['Children'],9997555627,0.0,1
50921,Being Bullied,Joy Berry,Help Me Be Good About Being Bullied explains w...,Hardcover,https://images.gr-assets.com/books/1494546931m...,1989-01-01,Smithmark Pub,NaN,3.78,12,['Children'],9999669972,0.0,1

In [17]:
books.drop(columns=['image_url'])

,id,title,authors,description,book_cover,release_date,publisher,number_of_pages,average_rating,number_of_ratings,categories,isbn,new_average_rating,new_number_of_ratings
0,0001053744,Pearl and Sir Orfeo,J. R. R. Tolkien,"This 14th-century poem, translated into modern...",Audiobook,NaN,Trafalgar Square Publishing,2.0,3.90,30,['Poetry'],0001053744,5.0,1
1,0001821504,The Adventures of Paddington,Michael Bond,The Adventures of Paddingtonis a special editi...,Hardcover,1970-01-01,HarperCollins Publishers,NaN,4.13,203,['Children'],0001821504,0.0,1
2,0001837397,Autumn Story,Jill Barklem,Step into the exquisite miniature world of the...,Hardcover,NaN,William Collins Sons Co Ltd,NaN,4.43,34,['Children'],0001837397,3.0,3
3,000184251X,"February's Road (Callendars, Book 2)",John Verney,"Augustus Callendar, a newspaper correspondent,...",NaN,1987-01-01,HarperCollins Publishers,NaN,4.50,20,['Children'],000184251X,0.0,2
4,0001981625,The Sea Of Tranquility,Mark Haddon,Leading up to the 40th anniversary of the firs...,Hardcover,NaN,HarperCollins Publishers,32.0,3.57,83,['Children'],0001981625,4.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50917,9997410440,Nine Hours to Rama,Stanley Wolpert,"""This is a terrifying, yet inspiring novel. As...",Hardcover,1962-01-01,Random House (T),376.0,3.75,51,"['History, Biology']",9997410440,10.0,1
50918,9997412958,The White Witch,Elizabeth Goudge,"Romantic tale set in 17th-century England, whe...",NaN,1958-01-01,Putnam Pub Group (T),NaN,3.99,10,"['History, Biology']",9997412958,10.0,1
50919,9997531590,World's End,Upton Sinclair,World's End is the first novel in Upton Sincla...,NaN,NaN,Penguin USA (T),NaN,4.02,298,"['History, Biology']",9997531590,0.0,1
50920,9997555627,My Sweet Orange Tree,Jose Mauro De Vasconcelos,"Five-year-old Zeze lives in Rio de Janeiro, in...",Hardcover,NaN,Random House (T),208.0,4.37,685,['Children'],9997555627,0.0,1
50921,9999669972,Being Bullied,Joy Berry,Help Me Be Good About Being Bullied explains w...,Hardcover,1989-01-01,Smithmark Pub,NaN,3.78,12,['Children'],9999669972,0.0,1

In [18]:
all_ratings = pd.merge(ratings, books, on='isbn')

In [19]:
all_ratings

,User-ID,Book-Rating,isbn,Location,Age,id,title,authors,description,book_cover,image_url,release_date,publisher,number_of_pages,average_rating,number_of_ratings,categories,new_average_rating,new_number_of_ratings
0,276727,0,0446520802,"h, new south wales, australia",16.0,0446520802,The Notebook,Nicholas Sparks,"A man with a faded, well-worn notebook open in...",Hardcover,https://images.gr-assets.com/books/1307040326m...,NaN,Warner Books,214.0,4.07,2243,['Romance'],4.060345,116
1,278418,0,0446520802,"omaha, nebraska, usa",NaN,0446520802,The Notebook,Nicholas Sparks,"A man with a faded, well-worn notebook open in...",Hardcover,https://images.gr-assets.com/books/1307040326m...,NaN,Warner Books,214.0,4.07,2243,['Romance'],4.060345,116
2,638,0,0446520802,"san diego, california, usa",20.0,0446520802,The Notebook,Nicholas Sparks,"A man with a faded, well-worn notebook open in...",Hardcover,https://images.gr-assets.com/books/1307040326m...,NaN,Warner Books,214.0,4.07,2243,['Romance'],4.060345,116
3,3363,0,0446520802,"knoxville, tennessee, usa",29.0,0446520802,The Notebook,Nicholas Sparks,"A man with a faded, well-worn notebook open in...",Hardcover,https://images.gr-assets.com/books/1307040326m...,NaN,Warner Books,214.0,4.07,2243,['Romance'],4.060345,116
4,7158,10,0446520802,"omaha, nebraska, usa",30.0,0446520802,The Notebook,Nicholas Sparks,"A man with a faded, well-worn notebook open in...",Hardcover,https://images.gr-assets.com/books/1307040326m...,NaN,Warner Books,214.0,4.07,2243,['Romance'],4.060345,116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386280,274446,4,0451526023,"cleveland, ohio, usa",22.0,0451526023,My Secret Life: An Erotic Diary of Victorian L...,James R. Kincaid,'My Secret Life' is perhaps the most infamous ...,Paperback,https://s.gr-assets.com/assets/nophoto/book/11...,NaN,Signet Classics,576.0,3.45,242,"['History, Biology']",4.000000,1
386281,274839,0,3442133173,"zÃ¼rich, zÃ¼rich, switzerland",50.0,3442133173,"Ich, Prinzessin Aus Dem Hause Al Saud / Ich, P...",Jean P. Sasson,Think of Saudi Arabia and what do you see? Ter...,NaN,https://s.gr-assets.com/assets/nophoto/book/11...,2001-01-01,Goldmann,287.0,4.00,19,"['History, Biology']",0.000000,1
386282,275163,7,1569313725,"gaithersburg, maryland, usa",NaN,1569313725,Secret Comics Japan: Underground Comics Now,Hyoe Narita,Selected by a former editor of the acclaimed m...,Paperback,https://s.gr-assets.com/assets/nophoto/book/11...,NaN,VIZ LLC,198.0,3.60,62,"['Comics, Graphics']",7.000000,1
386283,275531,0,1880238136,"little rock, arkansas, usa",NaN,1880238136,Song,Brigit Pegeen Kelly,Winner of the 1994 Lamont Poetry selection of ...,Paperback,https://s.gr-assets.com/assets/nophoto/book/11...,NaN,BOA Editions,90.0,4.32,652,['Poetry'],0.000000,1
386284,276647,0,0553571001,"arlington heights, illinois, usa",13.0,0553571001,Christmas with Anne and Other Holiday Stories,L. M. Montgomery,Share Anne's delight at receiving the dress of...,Mass Market Paperback,https://s.gr-assets.com/assets/nophoto/book/11...,NaN,Starfire,224.0,3.86,909,['Children'],0.000000,1

In [20]:
all_ratings.to_csv('all_ratings.csv')

In [ ]:
book_rating_with_langcode_eng_only